name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^9.1.0
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  # google_fonts: ^6.1.0
  fl_chart: ^0.66.2
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  video_thumbnail: ^0.5.3
  wave: ^0.2.2
  youtube: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
