# Generated by Django 4.1.5 on 2024-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('stage_fear_score', models.FloatField(blank=True, null=True)),
                ('boldness_score', models.FloatField(blank=True, null=True)),
                ('communication_skills_score', models.FloatField(blank=True, null=True)),
                ('vocabulary_usage_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
