# Generated by Django 4.1.5 on 2024-01-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='boldness_score',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='communication_skills_score',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='stage_fear_score',
        ),
        migrations.RemoveField(
            model_name='uservideo',
            name='vocabulary_usage_score',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='additional_feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='face_emotion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uservideo',
            name='voice_emotion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
