# Generated by Django 4.1.5 on 2024-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videotips'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='video_thumbnail',
            field=models.ImageField(default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
