# Generated by Django 4.1.5 on 2024-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uservideo_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservideo',
            name='video_thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
