# Generated by Django 4.1.5 on 2024-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_uservideo_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='uservideo',
            name='performance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
